m = {
    '日本語' : {
        'rem-main-title': '備忘録',

        'rem-c-load-ttl' : 'エラー',
        'rem-c-load-msg' : '設定ファイルが読めません。',
        'rem-c-load-btn' : '継続できません。',
        'rem-l-pass': 'パスワード:',
        'rem-l-item': '項目:',
        'rem-l-cont': '内容:',
        'rem-b-show': '照会',
        'rem-b-add': '記録',
        'rem-b-upd': '更新',
        'rem-b-fgt': '削除',
        'rem-b-list': '一覧',
        'rem-me-ope': '編集',
        'rem-me-ope-rm': '削除',
        'rem-me-ope-re': '項目名の変更',
        'rem-me-sh': '表示',
        'rem-me-sh-item': '項目',
        'rem-me-sh-hint': 'ヒント',
        'rem-me-se': '設定',
        'rem-me-se-conf': '動作設定',

        'rem-me-da': 'マイグレート',
        'rem-me-da-ex': 'エクスポート',
        'rem-me-da-im': 'インポート',

        'rem-cp-de-ttl1': 'エラー',
        'rem-cp-de-msg1': 'パスワードを入力してください。',
        'rem-cp-de-btn1': 'はい',
        'rem-cp-de-ttl2': 'エラー',
        'rem-cp-de-msg2': 'パスワードが正しくありません。',
        'rem-cp-de-btn2': '再入力',

        'rem-sh-de-ttl1': 'エラー',
        'rem-sh-de-msg1': '項目を入れてください。',
        'rem-sh-de-btn1': 'OK',
        'rem-sh-de-ttl2': 'エラー',
        'rem-sh-de-msg2': '項目がみつかりません。',
        'rem-sh-de-btn2': 'OK',
        'rem-sh-di-ttl1': '情報',
        'rem-sh-di-msg1': 'クリップボードにコピーしました。',
        'rem-sh-di-btn1': 'OK',
        'rem-sh-misc': '...以下略',

        'rem-up-de-ttl1': 'エラー',
        'rem-up-de-msg1': '項目を入れてください。',
        'rem-up-de-btn1': 'OK',
        'rem-up-de-ttl2': 'エラー',
        'rem-up-de-msg2': '項目がみつかりません。',
        'rem-up-de-btn2': 'OK',
        'rem-up-de-ttl3': 'エラー',
        'rem-up-de-msg3': '内容がありません。',
        'rem-up-de-btn3': 'OK',
        'rem-up-di-ttl1': '情報',
        'rem-up-di-msg1': '変更しました。',
        'rem-up-di-btn1': '戻る',

        'rem-ad-de-ttl1': 'エラー',
        'rem-ad-de-msg1': '項目を入れてください。',
        'rem-ad-de-btn1': 'OK',
        'rem-ad-de-ttl2': 'エラー',
        'rem-ad-de-msg2': '内容を入れてください。',
        'rem-ad-de-btn2': 'OK',
        'rem-ad-de-ttl3': 'エラー',
        'rem-ad-de-msg3': 'その項目は既に存在します。',
        'rem-ad-de-btn3': 'OK',
        'rem-ad-di-ttl1': '情報',
        'rem-ad-di-msg1': '情報を記録しました。',
        'rem-ad-di-btn1': 'OK',

        'rem-rm-de-ttl1': 'エラー',
        'rem-rm-de-msg1': '項目を入れてください。',
        'rem-rm-de-btn1': 'OK',
        'rem-rm-de-ttl2': '警告',
        'rem-rm-de-msg2': '本当にその情報を削除しますか？',
        'rem-rm-de-btn2-ok': '消去',
        'rem-rm-de-btn2-ca': 'Cancel',
        'rem-rm-di-ttl1': '情報',
        'rem-rm-di-msg1': '削除を中止しました。',
        'rem-rm-di-btn1': 'OK',
        'rem-rm-de-ttl3': 'エラー',
        'rem-rm-de-msg3': '項目がみつかりません。',
        'rem-rm-de-btn3': 'OK',
        'rem-rm-de-ttl4': 'エラー',
        'rem-rm-de-msg4': '操作中に項目が失われました。',
        'rem-rm-de-btn4': 'OK',
        'rem-rm-di-ttl2': '情報',
        'rem-rm-di-msg2': '消去しました。',
        'rem-rm-di-btn2': 'OK',

        'rem-re-de-ttl1': 'エラー',
        'rem-re-de-msg1': '項目名を入れてください。',
        'rem-re-de-btn1': '戻る',
        'rem-re-ds-ttl1': 'エラー',
        'rem-re-ds-msg1': '新しい項目名を入れてください。',
        'rem-re-ds-btn1-ok': 'はい',
        'rem-re-ds-btn1-ca': 'キャンセル',
        'rem-re-de-ttl2': 'エラー',
        'rem-re-de-msg2': 'その項目はすでにあります。'
            '変更したいときは先にその項目を削除してください。',
        'rem-re-de-btn2': 'はい',
        'rem-re-de-ttl3': 'エラー',
        'rem-re-de-msg3': '前の項目名と同じです。',
        'rem-re-de-btn3': 'はい',
        'rem-re-di-ttl1': '情報',
        'rem-re-di-msg1': '変更しました。',
        'rem-re-di-btn1': '戻る',
        'rem-re-de-ttl4': 'エラー',
        'rem-re-de-msg4': 'その項目はありません。',
        'rem-re-de-btn4': '戻る',

        'rem-li-di-ttl1': '情報',
        'rem-li-di-msg1': 'まだ情報が登録されていません。',
        'rem-li-di-btn1': 'OK',
        'rem-li-di-ttl2': '情報',
        'rem-li-di-msg2': '項目一覧',
        'rem-li-di-btn2': 'OK',

        'rem-hi-di-ttl1': '情報',
        'rem-hi-di-msg1': 'パスワードのヒントです。',
        'rem-hi-di-btn1': 'OK',

        'rem-qu-dw-ttl1': '警告',
        'rem-qu-dw-msg1': '本当に終了しますか？',
        'rem-qu-dw-dtl1': '使用中に回復できないエラーが発生しています。',
        'rem-qu-dw-btn1-ok': '終了',
        'rem-qu-dw-btn1-ca': 'Cancel',

        'rem-ex-df-ttl1': '出力先ファイル',
        'rem-ex-de-ttl1': 'エラー',
        'rem-ex-de-msg1': 'ファイルの書き込みに失敗しました。',
        'rem-ex-de-btn1': '戻る',

        'rem-im-df-ttl1': '入力元ファイル',
        'rem-im-de-ttl1': 'エラー',
        'rem-im-de-msg1': 'フォーマットが不正です。',
        'rem-im-de-btn1': '戻る',
        'rem-im-dw-ttl1': '警告',
        'rem-im-dw-msg1': 'すでにDBに存在している項目があります。'
                        '上書きしますか？',
        'rem-im-dw-btn1-ok': 'はい',
        'rem-im-dw-btn1-ca': 'いいえ',
        'rem-im-de-ttl2': 'エラー',
        'rem-im-de-msg2': 'CSVファイルにカラム数が2でない行があります。',
        'rem-im-de-btn2': '戻る',
        'rem-im-de-ttl3': 'エラー',
        'rem-im-de-msg3': '不正なJSONファイルです。',
        'rem-im-de-btn3': '戻る',
        'rem-im-de-ttl4': 'エラー',
        'rem-im-de-msg4': 'すでにDBに存在する項目があります。',
        'rem-im-de-btn4': '戻る',

        'reg-da-de-ttl1': '緊急',
        'reg-da-de-msg-r': 'DBファイルの読み込みに失敗しました。',
        'reg-da-de-msg-w': 'DBファイルの書き込みに失敗しました。',
        'reg-da-de-msg-c': 'DBファイルの読み書きに失敗しました。',

        'reg-lo-dw-ttl1': '情報',
        'reg-lo-dw-msg1': 'DBファイルが見当たらないため、'
            '初期化が必要です。\n初期化しますか？',
        'reg-lo-dw-btn1-ok': 'はい',
        'reg-lo-dw-btn1-ca': 'Cancel',
        'reg-lo-in-ttl1': '情報',
        'reg-lo-in-msg1': '終了します。',
        'reg-lo-in-btn1': 'はい',
        'reg-lo-da-ttl1': '入力',
        'reg-lo-da-msg1': 'パスワードのヒントを入力してください。',
        'reg-lo-da-btn1-ok': 'はい',
        'reg-lo-da-btn1-ca': '止める',
        'reg-lo-de-ttl1': 'エラー',
        'reg-lo-de-msg1': 'ファイル形式が変更になりました。'
            '修正してください。',
        'reg-lo-de-btn1': 'OK',

        'reg-gp-da-ttl1': 'パスワードの設定',
        'reg-gp-da-msg1': 'パスワードを入力してください。\n'
            'パスワードを忘れた場合、復旧手段はありません。',
        'reg-gp-da-btn1-ok': 'はい',
        'reg-gp-da-btn1-ca': 'キャンセル',
        'reg-gp-da-ttl2': 'パスワードの設定',
        'reg-gp-da-msg2': '照合のためもう一度入力してください。',
        'reg-gp-da-btn2-ok': 'はい',
        'reg-gp-da-btn2-ca': 'キャンセル',
        'reg-gp-de-ttl1': 'エラー',
        'reg-gp-de-msg1': 'パスワードが不一致です。',
        'reg-gp-de-btn1': 'もう一度',

        'reg-sa-dw-ttl1': '警告',
        'reg-sa-dw-msg1': '操作中にエラーが記録されています。'
            '本当に保存しますか？',
        'reg-sa-dw-btn1-ok': '保存',
        'reg-sa-dw-btn1-ca': 'Cancel',

        'reg-sa-di-ttl1': '情報',
        'reg-sa-di-msg1': 'DBファイルに対する対処が必要な'
            '可能性があります。',
        'reg-sa-di-btn1': 'OK',

        'reg-qu-de-ttl1': 'エラー',
        'reg-qu-de-msg1': '終了に失敗しました。',
        'reg-qu-de-btn1': '受諾',

        'set-in-ttl': '設定',
        'set-in-frm1': 'クリップボード消去',
        'set-in-lbl1': 'クリップボードを消す秒数\n'
            '自動で消したくなければ"0"とする。',
        'set-in-btn1': '適用',
        'set-in-frm2': '言語',
        'set-in-lbl2': '表示する言語',
    },
    'English' : {
        'rem-main-title': 'Remember',

        'rem-c-load-ttl' : 'Error',
        'rem-c-load-msg' : "Cant't read config file.",
        'rem-c-load-btn' : 'Abort',
        'rem-l-pass': 'Password:',
        'rem-l-item': 'Item:',
        'rem-l-cont': 'Content:',
        'rem-b-show': 'Show',
        'rem-b-add': 'Record',
        'rem-b-upd': 'Update',
        'rem-b-fgt': 'Remove',
        'rem-b-list': 'List',

        'rem-me-ope': 'Edit',
        'rem-me-ope-rm': 'Remove',
        'rem-me-ope-re': 'Rename item',

        'rem-me-sh': 'Info',
        'rem-me-sh-item': 'List items',
        'rem-me-sh-hint': 'Password hint',

        'rem-me-se': 'Setting',
        'rem-me-se-conf': 'Function',

        'rem-me-da': 'Migration',
        'rem-me-da-ex': 'Export',
        'rem-me-da-im': 'Import',

        'rem-cp-de-ttl1': 'Error',
        'rem-cp-de-msg1': 'Input password.',
        'rem-cp-de-btn1': 'OK',
        'rem-cp-de-ttl2': 'Error',
        'rem-cp-de-msg2': 'Input correct password.',
        'rem-cp-de-btn2': 'OK',

        'rem-cp-de-ttl1': 'Error',
        'rem-cp-de-msg1': 'Input your password.',
        'rem-cp-de-btn1': 'OK',
        'rem-cp-de-ttl2': 'Error',
        'rem-cp-de-msg2': 'Password unmatch.',
        'rem-cp-de-btn2': 'OK',

        'rem-sh-de-ttl1': 'Error',
        'rem-sh-de-msg1': 'Input an item.',
        'rem-sh-de-btn1': 'OK',
        'rem-sh-de-ttl2': 'Error',
        'rem-sh-de-msg2': 'Item not found',
        'rem-sh-de-btn2': 'OK',
        'rem-sh-di-ttl1': 'Info',
        'rem-sh-di-msg1': 'The data is copied to clip board.',
        'rem-sh-di-btn1': 'OK',
        'rem-sh-misc': '...and so on.',

        'rem-up-de-ttl1': 'Error',
        'rem-up-de-msg1': 'Input an item.',
        'rem-up-de-btn1': 'OK',
        'rem-up-de-ttl2': 'Error',
        'rem-up-de-msg2': 'Input an item.',
        'rem-up-de-btn2': 'OK',
        'rem-up-de-ttl3': 'Error',
        'rem-up-de-msg3': 'Input content.',
        'rem-up-de-btn3': 'OK',
        'rem-up-di-ttl1': 'Info',
        'rem-up-di-msg1': 'Updated.',
        'rem-up-di-btn1': 'Return',

        'rem-ad-de-ttl3': 'Error',
        'rem-ad-de-msg3': 'That item is existing.',
        'rem-ad-de-btn3': 'OK',
        'rem-ad-di-ttl1': 'Info',
        'rem-ad-di-msg1': 'New memory is recorded',
        'rem-ad-di-btn1': 'OK',

        'rem-rm-de-ttl1': 'Error',
        'rem-rm-de-msg1': 'Input an item',
        'rem-rm-de-btn1': 'OK',
        'rem-rm-de-ttl2': 'Warning',
        'rem-rm-de-msg2': 'You are about to remove. Are you sure?',
        'rem-rm-de-btn2-ok': 'OK',
        'rem-rm-de-btn2-ca': 'Cancel',
        'rem-rm-di-ttl1': 'Info',
        'rem-rm-di-msg1': 'Memory is remained.',
        'rem-rm-di-btn1': 'OK',
        'rem-rm-de-ttl3': 'Error',
        'rem-rm-de-msg3': 'There is no such item.',
        'rem-rm-de-btn3': 'OK',
        'rem-rm-de-ttl4': 'Error',
        'rem-rm-de-msg4': 'The target memory was lost.',
        'rem-rm-de-btn4': 'OK',
        'rem-rm-di-ttl2': 'Info',
        'rem-rm-di-msg2': 'The memory is removed.',
        'rem-rm-di-btn2': 'OK',

        'rem-re-ds-ttl1': 'Error',
        'rem-re-ds-msg1': 'Enter new item name.',
        'rem-re-ds-btn1-ok': 'OK',
        'rem-re-ds-btn1-ca': 'Cancel',
        'rem-re-de-ttl2': 'Error',
        'rem-re-de-msg2': 'That item exists already.'
            'Remove that item before rename.',
        'rem-re-de-btn2': 'OK',
        'rem-re-de-ttl3': 'Error',
        'rem-re-de-msg3': 'That item is not changed as previous.',
        'rem-re-de-btn3': 'Return',
        'rem-re-di-ttl1': 'Info',
        'rem-re-di-msg1': 'The key is updated.',
        'rem-re-di-btn1': 'Return',
        'rem-re-de-ttl4': 'Error',
        'rem-re-de-msg4': 'That item does not exit.',
        'rem-re-de-btn4': 'Return',


        'rem-li-di-ttl1': 'Info',
        'rem-li-di-msg1': 'There is no memories.',
        'rem-li-di-btn1': 'OK',
        'rem-li-di-ttl2': 'Info',
        'rem-li-di-msg2': 'Here you are.',
        'rem-li-di-btn2': 'OK',

        'rem-hi-di-ttl1': 'Info',
        'rem-hi-di-msg1': 'Remember your password with a hint.',
        'rem-hi-di-btn1': 'OK',

        'rem-qu-dw-ttl1': 'Warning',
        'rem-qu-dw-msg1': 'Are you realy quit?',
        'rem-qu-dw-dtl1': 'While using this application, '
            'there might occur some errors.',
        'rem-qu-dw-btn1-ok': 'Quit',
        'rem-qu-dw-btn1-ca': 'Cancel',

        'rem-ex-df-ttl1': 'Output file',
        'rem-ex-de-ttl1': 'Error',
        'rem-ex-de-msg1': 'Failed to write file.',
        'rem-ex-de-btn1': 'Return',

        'rem-im-df-ttl1': 'Input file',
        'rem-im-de-ttl1': 'Eror',
        'rem-im-de-msg1': 'Illegal format.',
        'rem-im-de-btn1': 'Return',
        'rem-im-dw-ttl1': 'Warning',
        'rem-im-dw-msg1': 'Some data exists already in DB. '
                        'Do you overwrite them?',
        'rem-im-dw-btn1-ok': 'Yes',
        'rem-im-dw-btn1-ca': 'No',
        'rem-im-de-ttl2': 'Error',
        'rem-im-de-msg2': 'Some rows do not cotain in 2 columns.',
        'rem-im-de-btn2': 'Return',
        'rem-im-de-ttl3': 'Error',
        'rem-im-de-msg3': 'Invalid JSON file.',
        'rem-im-de-btn3': 'Return',
        'rem-im-de-ttl4': 'Error',
        'rem-im-de-msg4': 'Some data exists already in DB.',
        'rem-im-de-btn4': 'Return',

        'reg-da-de-ttl1': 'Emergency',
        'reg-da-de-msg-r': 'Failed to write DB.',
        'reg-da-de-msg-w': 'Failed to read DB',
        'reg-da-de-msg-c': 'Failed to update DB',

        'reg-lo-dw-ttl1': 'Info',
        'reg-lo-dw-msg1': 'DB file no found.\nIs this the first launch of this apps?',
        'reg-lo-dw-btn1-ok': 'Yes',
        'reg-lo-dw-btn1-ca': 'No',
        'reg-lo-in-ttl1': 'Info',
        'reg-lo-in-msg1': 'See you again.',
        'reg-lo-in-btn1:': 'OK',
        'reg-lo-da-ttl1': 'Enter',
        'reg-lo-da-msg1': 'Input a hint for password.',
        'reg-lo-da-btn1-ok': 'OK',
        'reg-lo-da-btn1-ca': 'Cancel',
        'reg-lo-de-ttl1': 'Error',
        'reg-lo-de-msg1': 'DB file of previous version found.\n'
            'Do version up before launch.',
        'reg-lo-de-btn1': 'OK',

        'reg-gp-da-ttl1': 'Info',
        'reg-gp-da-msg1': 'Input PASSWORD.\n'
            'If you forgot password, there is NO WAY to rescue them.',
        'reg-gp-da-btn1-ok': 'Yes',
        'reg-gp-da-btn1-ca': 'Cancel',
        'reg-gp-da-ttl2': 'Info',
        'reg-gp-da-msg2': 'Confirm your password.',
        'reg-gp-da-btn2-ok': 'OK',
        'reg-gp-da-btn2-ca': 'Cancel',
        'reg-gp-de-ttl1': 'Error',
        'reg-gp-de-msg1': 'You entered the different passwords.',
        'reg-gp-de-btn1': 'Again',

        'reg-sa-dw-ttl1': 'Warning',
        'reg-sa-dw-msg1': 'There occured some erros while using app.\nDo you save anyway?',
        'reg-sa-dw-btn1-ok': 'Yes',
        'reg-sa-dw-btn1-ca': 'Cancel',

        'reg-sa-di-ttl1': 'Info',
        'reg-sa-di-msg1': 'God may bless you.',
        'reg-sa-di-btn1': 'OK',

        'reg-qu-de-ttl1': 'Error',
        'reg-qu-de-msg1': 'Failed to quit.',
        'reg-qu-de-btn1': 'OK',

        'set-in-ttl': 'Settings',
        'set-in-frm1': 'Remove clibboard.',
        'set-in-lbl1': 'Interval fo removal (in secomds)\n'
            'Set 0 for no removal.',
        'set-in-btn1': 'Apply',
        'set-in-frm2': 'Language',
        'set-in-lbl2': 'Select',
    },
    'にゃあ語' : {
        'rem-main-title': 'にゃあの記録～おさかなにゃ！',

        'rem-c-load-ttl' : 'いきなりエラーにゃ！',
        'rem-c-load-msg' : '設定ファイルが読めないにゃ・・・',
        'rem-c-load-btn' : '何とかしてにゃ・・・',
        'rem-l-pass' : '合言葉にゃ！',
        'rem-l-item': '何のことにゃ？',
        'rem-l-cont': '聞かせるにゃ',
        'rem-b-show': '思い出すにゃ',
        'rem-b-add': '覚えるにゃ',
        'rem-b-upd': '覚えなおすにゃ',
        'rem-b-fgt': '忘れるにゃ',
        'rem-b-list': '一覧にゃ',
        'rem-me-ope': '編集するにゃ',
        'rem-me-ope-rm': '思い出を消すにゃよ？',
        'rem-me-ope-re': '名前を変えるにゃよ？',
        'rem-me-sh': '教えるにゃ',
        'rem-me-sh-item': '今まで覚えたことにゃ',
        'rem-me-sh-hint': '合言葉を忘れたにゃ！',
        'rem-me-se': '設定にゃ',
        'rem-me-se-conf': '動作設定にゃ',
        'rem-me-da': 'ノートにゃ',
        'rem-me-da-ex': '記憶を書き留めるにゃ',
        'rem-me-da-im': '記録を取り込むにゃ',

        'rem-cp-de-ttl1': 'あわてるにゃ',
        'rem-cp-de-msg1': '合言葉を入れてないじゃにゃいか',
        'rem-cp-de-btn1': 'もう一度にゃ',
        'rem-cp-de-ttl2': 'あせるにゃ',
        'rem-cp-de-msg2': '合言葉が違うにゃ！\nよく見直すにゃ。',
        'rem-cp-de-btn2': '落ち着くにゃ',

        'rem-sh-de-ttl1': '無理にゃよ',
        'rem-sh-de-msg1': '知りたいことをおしえてくれにゃ・・・',
        'rem-sh-de-btn1': 'またくるにゃ',
        'rem-sh-de-ttl2': 'それ何にゃ？',
        'rem-sh-de-msg2': 'そんなことは知らないにゃ・・・',
        'rem-sh-de-btn2': 'よく思い出すにゃ',
        'rem-sh-di-ttl1': 'みつけたにゃ！',
        'rem-sh-di-msg1': '思い出したにゃ！\n'
            'クリップボードにコピーしたにゃ。',
        'rem-sh-di-btn1': 'ああ、そうっだったにゃぁ',
        'rem-sh-misc': '...むにゃむにゃ',

        'rem-up-de-ttl1': '無理にゃよ',
        'rem-up-de-msg1': '覚えなおしたいことを教えてくれにゃ・・・',
        'rem-up-de-btn1': 'またくるにゃ',
        'rem-up-de-ttl2': 'それ何にゃ？',
        'rem-up-de-msg2': 'そんなことは知らないにゃ',
        'rem-up-de-btn2': 'よく思い出すにゃ',
        'rem-up-de-ttl3': '内容がないにゃ',
        'rem-up-de-msg3': '実は忘れたいのかにゃ？',
        'rem-up-de-btn3': 'またくるにゃ',
        'rem-up-di-ttl1': 'できたにゃ',
        'rem-up-di-msg1': '覚えなおしたにゃ。',
        'rem-up-di-btn1': '心変わりにゃ？',

        'rem-ad-de-ttl1': '無理にゃよ',
        'rem-ad-de-msg1': '覚えたいことを教えてくれにゃ・・・',
        'rem-ad-de-btn1': 'またくるにゃ',
        'rem-ad-de-ttl2': '意味ないにゃ',
        'rem-ad-de-msg2': '中身が空っぽにゃが？',
        'rem-ad-de-btn2': 'またくるにゃ',
        'rem-ad-de-ttl3': 'やめるにゃ',
        'rem-ad-de-msg3': 'その項目はもうあるにゃよ？\n'
            '上書きしたいなら思え直すにゃ',
        'rem-ad-de-btn3': '考え直すにゃ',
        'rem-ad-di-ttl1': 'できたにゃ',
        'rem-ad-di-msg1': '新しいことを覚えたにゃ。',
        'rem-ad-di-btn1': '忘れないにゃ',

        'rem-rm-de-ttl1': '無理にゃよ',
        'rem-rm-de-msg1': '何を忘れたいにゃ？',
        'rem-rm-de-btn1': 'またくるにゃ',
        'rem-rm-de-ttl2': 'もう一度考えるにゃ',
        'rem-rm-de-msg2': 'それは本当に忘れていいことにゃ？\n'
            'もう二度と思い出せないにゃよ？',
        'rem-rm-de-btn2-ok': '忘れるにゃ',
        'rem-rm-de-btn2-ca': '嫌にゃ！',
        'rem-rm-di-ttl1': 'わかったにゃ',
        'rem-rm-di-msg1': '忘れられないこともあるにゃ・・・',
        'rem-rm-di-btn1': '大切な思い出にゃん',
        'rem-rm-de-ttl3': 'それ何にゃ？',
        'rem-rm-de-msg3': 'そんな思い出はないにゃ・・・',
        'rem-rm-de-btn3': 'よく思い出すにゃ',
        'rem-rm-de-ttl4': 'ありえないにゃ',
        'rem-rm-de-msg4': 'さっきまで覚えていたのに忘れたにゃ！\n'
            '他にどっかのにゃんこがさわってないかにゃ？\n'
            'アプリを２つ起ち上げているとか',
        'rem-rm-de-btn4': '怖いにゃ・・',
        'rem-rm-di-ttl2': 'できたにゃ',
        'rem-rm-di-msg2': 'もうそのことは忘れたにゃ。\n'
                '忘れることも大切にゃ。',
        'rem-rm-di-btn2': '諸行無常にゃねえ',

        'rem-re-de-ttl1': 'わからないにゃ',
        'rem-re-de-msg1': '何を変えたいにゃ？',
        'rem-re-de-btn1': 'もう一度にゃ',
        'rem-re-ds-ttl1': '教えるにゃ',
        'rem-re-ds-msg1': '何に変えるにゃ？',
        'rem-re-ds-btn1-ok': 'これでいいにゃ？',
        'rem-re-ds-btn1-ca': 'やめるにゃ！',
        'rem-re-de-ttl2': 'やめるにゃ',
        'rem-re-de-msg2': 'それはもうあるにゃよ。'
            'どうしてもというにゃら、先にそれを忘れるにゃ。',
        'rem-re-de-btn2': 'わかったにゃ',
        'rem-re-de-ttl3': 'だめにゃ',
        'rem-re-de-msg3': '同じにゃよ！',
        'rem-re-de-btn3': 'うっかりにゃ',
        'rem-re-di-ttl1': 'わかったにゃ',
        'rem-re-di-msg1': '変えたにゃ',
        'rem-re-di-btn1': '納得したにゃ',
        'rem-re-de-ttl4': 'だめにゃ',
        'rem-re-de-msg4': 'そんなことは知らないにゃよ・・・',
        'rem-re-de-btn4': 'うっかりにゃ',

        'rem-li-di-ttl1': 'にゃぁぁ',
        'rem-li-di-msg1': 'にゃあはまだ何もおぼえてないにゃん・・・',
        'rem-li-di-btn1': 'またくるにゃ',
        'rem-li-di-ttl2': 'にゃ～ん',
        'rem-li-di-msg2': '忘れたにゃ？特別に見せてやるにゃ。'
                'おさかなもってくるにゃ。',
        'rem-li-di-btn2': 'わかったにゃ！',

        'rem-hi-di-ttl1': 'ヒントにゃ',
        'rem-hi-di-msg1': 'パスワード忘れたにゃ？ヒントで思い出すにゃ！',
        'rem-hi-di-btn1': '思い出したにゃ',

        'rem-qu-dw-ttl1': '終わるにゃ',
        'rem-qu-dw-msg1': 'もう帰ってもいいにゃん？',
        'rem-qu-dw-dtl1': '何か故障があったにゃ・・・\n覚悟はいいにゃ？',
        'rem-qu-dw-btn1-ok': 'また会うにゃ～',
        'rem-qu-dw-btn1-ca': '待つにゃ！',

        'rem-ex-df-ttl1': 'どこに吸いだすにゃ？',
        'rem-ex-de-ttl1': 'だめにゃ',
        'rem-ex-de-msg1': 'ファイルに書けなかったにゃ。',
        'rem-ex-de-btn1': '調べるにゃ！',

        'rem-im-df-ttl1': 'どのファイルから吸込むにゃ？',
        'rem-im-de-ttl1': 'だめにゃ',
        'rem-im-de-msg1': '書き方を間違えているようにゃが？',
        'rem-im-de-btn1': '調べるにゃ！',
        'rem-im-dw-ttl1': '待つにゃ',
        'rem-im-dw-msg1': 'いくつかの項目ですでに覚えていることを'
                        '書き直してしまうにゃ。いいのかにゃ',
        'rem-im-dw-btn1-ok': '覚えなおすにゃ',
        'rem-im-dw-btn1-ca': 'や、やめるにゃ',
        'rem-im-de-ttl2': 'だめにゃ',
        'rem-im-de-msg2': 'CSVファイルにカラム数が2でない行があるにゃ。',
        'rem-im-de-btn2': '直すにゃ',
        'rem-im-de-ttl3': 'だめにゃ',
        'rem-im-de-msg3': 'JSONファイルに変なものが入っているにゃ。',
        'rem-im-de-btn3': '直すにゃ',
        'rem-im-de-ttl4': 'だめにゃ',
        'rem-im-de-msg4': 'ファイルの中に同じ項目があるにゃよ？',
        'rem-im-de-btn4': '直すにゃ',

        'reg-da-de-ttl1': '一大事にゃ！！',
        'reg-da-de-msg-r': '記憶ファイルが読めないにゃ！なんとかするにゃ！',
        'reg-da-de-msg-w': '記憶ファイルに書き込めないにゃ！'
                        'なんとかするにゃ！',
        'reg-da-de-msg-c': '記憶ファイルに読み書きできないにゃ！'
                        'なんとかするにゃ！',

        'reg-lo-dw-ttl1': '初めてにゃ？',
        'reg-lo-dw-msg1': 'おみゃあさん、初めて見るにゃ。違うにゃ？\n'
                'もし初めてでないにゃら何かおかしいにゃ。\n'
                'にゃあのノートが見当たらないにゃ。\n'
                '初めてなら、これからおみゃあさん専用のノートを作るにゃ。',
        'reg-lo-dw-btn1-ok': '初めてにゃ！',
        'reg-lo-dw-btn1-ca': 'やめるにゃ！',

        'reg-gp-da-ttl1': '準備にゃ',
        'reg-gp-da-msg1': '秘密の合言葉を決めるにゃ。\n'
            '忘れたら何も思い出せなくなるにゃ。\n'
            'しっかり覚えるにゃ！',
        'reg-gp-da-btn1-ok': 'もちろんにゃ！',
        'reg-gp-da-btn1-ca': '今はやめておくにゃ',
        'reg-gp-da-ttl2': 'もう一度にゃ',
        'reg-gp-da-msg2': '念のためもう一度合言葉を教えるにゃ。',
        'reg-gp-da-btn2-ok': 'これにゃ！',
        'reg-gp-da-btn2-ca': '引き返すにゃ',
        'reg-gp-de-ttl1': 'あわてるでないにゃ',
        'reg-gp-de-msg1': 'パスワードが不一致にゃよ。',
        'reg-gp-de-btn1': '最初からにゃ',

        'reg-lo-in-ttl1': 'またにゃ！',
        'reg-lo-in-msg1': 'にゃあはいつでもここにいるにゃ。',
        'reg-lo-in-btn1': 'またにゃ！',

        'reg-lo-da-ttl1': '教えるにゃ',
        'reg-lo-da-msg1': '合言葉のヒントを決めるにゃ。',
        'reg-lo-da-btn1-ok': 'これにゃ',
        'reg-lo-da-btn1-ca': 'いらないにゃ',

        'reg-lo-de-ttl1': 'やめるにゃ！',
        'reg-lo-de-msg1': 'バージョンアップがあったようにゃよ？',
        'reg-lo-de-btn1': 'バージョンアップしてにゃ',

        'reg-sa-dw-ttl1': 'どうするにゃ？',
        'reg-sa-dw-msg1': '何かまずいことになってるにゃろ？本当に記録するにゃ？中身を書きだした方がいいんじゃにゃあか？',
        'reg-sa-dw-btn1-ok': 'するにゃ！',
        'reg-sa-dw-btn1-ca': 'や、やめるにゃ',

        'reg-sa-di-ttl1': '気を付けるにゃ',
        'reg-sa-di-msg1': 'なんとかしてくれにゃ・・・',
        'reg-sa-di-btn1': '祈るにゃ',

        'reg-qu-de-ttl1': 'あ～あ・・・',
        'reg-qu-de-msg1': 'まずいことになったにゃ。直しきれないにゃ',
        'reg-qu-de-btn1': '観念したにゃん！',

        'set-in-ttl': '設定するにゃ',
        # コピペの自動制御
        'set-in-frm1': 'クリップボード消すにゃ？',
        'set-in-lbl1': '何秒後にクリップボードを消すにゃ？\n'
            '自動で消したくなければ"0"とするにゃ。',
        'set-in-btn1': '納得したにゃ？',
        'set-in-frm2': '言葉を選ぶにゃ',
        'set-in-lbl2': '好きな言語を選ぶにゃ',
    },
}

